#ifndef ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
#define ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H

struct ElementoArbolBinarioBusqueda{
    int num;
    int esSkynerd;
};

#endif //ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
