#ifndef ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
#define ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H

struct ElementoArbolBinarioBusqueda{
    int num;
};

#endif //ARBOLBINARIOBUSQUEDA_ELEMENTOARBOLBINARIOBUSQUEDA_H
