#ifndef INC_01_IMPLEMENTACION_ELEMENTOARBOLBINARIO_H
#define INC_01_IMPLEMENTACION_ELEMENTOARBOLBINARIO_H

struct ElementoArbolBinario{
    int num;
};

#endif //INC_01_IMPLEMENTACION_ELEMENTOARBOLBINARIO_H